-- MySQL Script generated by MySQL Workbench
-- lun 01 dic 2014 18:31:45 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema offerta_didattica_DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `offerta_didattica_DB` ;

-- -----------------------------------------------------
-- Schema offerta_didattica_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `offerta_didattica_DB` ;
USE `offerta_didattica_DB` ;

-- -----------------------------------------------------
-- Table `offerta_didattica_DB`.`teaching`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerta_didattica_DB`.`teaching` ;

CREATE TABLE IF NOT EXISTS `offerta_didattica_DB`.`teaching` (
  `matricula` VARCHAR(10) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `abbreviation` VARCHAR(10) NOT NULL,
  `link` VARCHAR(500) NOT NULL,
  `year` INT(11) NOT NULL,
  `semester` INT(11) NOT NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `offerta_didattica_DB`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerta_didattica_DB`.`class` ;

CREATE TABLE IF NOT EXISTS `offerta_didattica_DB`.`class` (
  `title` VARCHAR(50) NOT NULL,
  `teaching_matricula` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`title`, `teaching_matricula`),
  INDEX `fk_class_teaching1_idx` (`teaching_matricula` ASC),
  CONSTRAINT `fk_class_teaching1`
    FOREIGN KEY (`teaching_matricula`)
    REFERENCES `offerta_didattica_DB`.`teaching` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `offerta_didattica_DB`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerta_didattica_DB`.`department` ;

CREATE TABLE IF NOT EXISTS `offerta_didattica_DB`.`department` (
  `abbreviation` INT(11) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `url_moodle` VARCHAR(200) NOT NULL,
  `token` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`abbreviation`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `offerta_didattica_DB`.`cycle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerta_didattica_DB`.`cycle` ;

CREATE TABLE IF NOT EXISTS `offerta_didattica_DB`.`cycle` (
  `cycle_number` INT(11) NOT NULL,
  `title` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cycle_number`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `offerta_didattica_DB`.`degree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerta_didattica_DB`.`degree` ;

CREATE TABLE IF NOT EXISTS `offerta_didattica_DB`.`degree` (
  `title` VARCHAR(50) NOT NULL,
  `matricula` VARCHAR(5) NOT NULL,
  `link` VARCHAR(500) NOT NULL,
  `department_abbreviation` INT(11) NOT NULL,
  `cycle` INT(11) NOT NULL,
  PRIMARY KEY (`matricula`, `department_abbreviation`, `cycle`),
  INDEX `fk_degree_department1_idx` (`department_abbreviation` ASC),
  INDEX `fk_degree_cycle1_idx` (`cycle` ASC),
  CONSTRAINT `fk_degree_department1`
    FOREIGN KEY (`department_abbreviation`)
    REFERENCES `offerta_didattica_DB`.`department` (`abbreviation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_degree_cycle1`
    FOREIGN KEY (`cycle`)
    REFERENCES `offerta_didattica_DB`.`cycle` (`cycle_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `offerta_didattica_DB`.`curriculum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerta_didattica_DB`.`curriculum` ;

CREATE TABLE IF NOT EXISTS `offerta_didattica_DB`.`curriculum` (
  `title` VARCHAR(100) NOT NULL,
  `degree_matricula` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`title`, `degree_matricula`),
  INDEX `fk_curriculum_degree1_idx` (`degree_matricula` ASC),
  CONSTRAINT `fk_curriculum_degree1`
    FOREIGN KEY (`degree_matricula`)
    REFERENCES `offerta_didattica_DB`.`degree` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `offerta_didattica_DB`.`module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerta_didattica_DB`.`module` ;

CREATE TABLE IF NOT EXISTS `offerta_didattica_DB`.`module` (
  `title` VARCHAR(50) NOT NULL,
  `teaching_matricula` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`title`, `teaching_matricula`),
  INDEX `fk_module_teaching1_idx` (`teaching_matricula` ASC),
  CONSTRAINT `fk_module_teaching1`
    FOREIGN KEY (`teaching_matricula`)
    REFERENCES `offerta_didattica_DB`.`teaching` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `offerta_didattica_DB`.`curriculum_has_teaching`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerta_didattica_DB`.`curriculum_has_teaching` ;

CREATE TABLE IF NOT EXISTS `offerta_didattica_DB`.`curriculum_has_teaching` (
  `teaching_matricula` VARCHAR(10) NOT NULL,
  `curriculum_title` VARCHAR(100) NOT NULL,
  `curriculum_id_degree` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`teaching_matricula`, `curriculum_title`, `curriculum_id_degree`),
  INDEX `fk_teaching_has_curriculum_curriculum1_idx` (`curriculum_title` ASC, `curriculum_id_degree` ASC),
  INDEX `fk_teaching_has_curriculum_teaching1_idx` (`teaching_matricula` ASC),
  CONSTRAINT `fk_teaching_has_curriculum_teaching1`
    FOREIGN KEY (`teaching_matricula`)
    REFERENCES `offerta_didattica_DB`.`teaching` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teaching_has_curriculum_curriculum1`
    FOREIGN KEY (`curriculum_title`)
    REFERENCES `offerta_didattica_DB`.`curriculum` (`title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'curriculum has many teaching\nand a teaching could be in many curriculum';


-- -----------------------------------------------------
-- Table `offerta_didattica_DB`.`curriculum_has_teaching`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerta_didattica_DB`.`curriculum_has_teaching` ;

CREATE TABLE IF NOT EXISTS `offerta_didattica_DB`.`curriculum_has_teaching` (
  `teaching_matricula` VARCHAR(10) NOT NULL,
  `curriculum_title` VARCHAR(100) NOT NULL,
  `curriculum_id_degree` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`teaching_matricula`, `curriculum_title`, `curriculum_id_degree`),
  INDEX `fk_teaching_has_curriculum_curriculum1_idx` (`curriculum_title` ASC, `curriculum_id_degree` ASC),
  INDEX `fk_teaching_has_curriculum_teaching1_idx` (`teaching_matricula` ASC),
  CONSTRAINT `fk_teaching_has_curriculum_teaching1`
    FOREIGN KEY (`teaching_matricula`)
    REFERENCES `offerta_didattica_DB`.`teaching` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teaching_has_curriculum_curriculum1`
    FOREIGN KEY (`curriculum_title`)
    REFERENCES `offerta_didattica_DB`.`curriculum` (`title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'curriculum has many teaching\nand a teaching could be in many curriculum';


-- -----------------------------------------------------
-- Table `offerta_didattica_DB`.`professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerta_didattica_DB`.`professor` ;

CREATE TABLE IF NOT EXISTS `offerta_didattica_DB`.`professor` (
  `email` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `offerta_didattica_DB`.`class_module_prof`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerta_didattica_DB`.`class_module_prof` ;

CREATE TABLE IF NOT EXISTS `offerta_didattica_DB`.`class_module_prof` (
  `class_title` VARCHAR(50) NOT NULL,
  `class_teaching_matricula` VARCHAR(10) NOT NULL,
  `module_title` VARCHAR(50) NOT NULL,
  `module_teaching_matricula` VARCHAR(10) NOT NULL,
  `professor_email` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`class_title`, `class_teaching_matricula`, `module_title`, `module_teaching_matricula`, `professor_email`),
  INDEX `fk_class_module_prof_module1_idx` (`module_title` ASC, `module_teaching_matricula` ASC),
  INDEX `fk_class_module_prof_professor1_idx` (`professor_email` ASC),
  CONSTRAINT `fk_class_module_prof_class1`
    FOREIGN KEY (`class_title` , `class_teaching_matricula`)
    REFERENCES `offerta_didattica_DB`.`class` (`title` , `teaching_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_module_prof_module1`
    FOREIGN KEY (`module_title` , `module_teaching_matricula`)
    REFERENCES `offerta_didattica_DB`.`module` (`title` , `teaching_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_module_prof_professor1`
    FOREIGN KEY (`professor_email`)
    REFERENCES `offerta_didattica_DB`.`professor` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `offerta_didattica_DB`.`teaching_esse3_content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerta_didattica_DB`.`teaching_esse3_content` ;

CREATE TABLE IF NOT EXISTS `offerta_didattica_DB`.`teaching_esse3_content` (
  `teaching_matricula` VARCHAR(10) NOT NULL,
  `html_content` VARCHAR(45) NULL,
  PRIMARY KEY (`teaching_matricula`),
  CONSTRAINT `fk_teaching_esse3_content_teaching1`
    FOREIGN KEY (`teaching_matricula`)
    REFERENCES `offerta_didattica_DB`.`teaching` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
