-- MySQL Script generated by MySQL Workbench
-- lun 01 dic 2014 18:24:07 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_integrazione
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_integrazione` ;

-- -----------------------------------------------------
-- Schema db_integrazione
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_integrazione` DEFAULT CHARACTER SET utf8 ;
USE `db_integrazione` ;

-- -----------------------------------------------------
-- Table `db_integrazione`.`Permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_integrazione`.`Permissions` ;

CREATE TABLE IF NOT EXISTS `db_integrazione`.`Permissions` (
  `idPermissions` INT NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `class` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPermissions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_integrazione`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_integrazione`.`Account` ;

CREATE TABLE IF NOT EXISTS `db_integrazione`.`Account` (
  `email` VARCHAR(100) NOT NULL COMMENT 'Nome con il quale l\'utente viene riconosciuto da un',
  `password` VARCHAR(45) NOT NULL,
  `typeOfAccount` VARCHAR(45) NULL DEFAULT NULL,
  `Permissions_idPermissions` INT NOT NULL,
  PRIMARY KEY (`email`, `Permissions_idPermissions`),
  INDEX `fk_Account_Permissions_idx` (`Permissions_idPermissions` ASC),
  CONSTRAINT `fk_Account_Permissions`
    FOREIGN KEY (`Permissions_idPermissions`)
    REFERENCES `db_integrazione`.`Permissions` (`idPermissions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabella adibita alla gestione dei dati principali per l\'acesso al sistema';


-- -----------------------------------------------------
-- Table `db_integrazione`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_integrazione`.`Department` ;

CREATE TABLE IF NOT EXISTS `db_integrazione`.`Department` (
  `abbreviation` VARCHAR(50) NOT NULL,
  `title` VARCHAR(50) NULL DEFAULT NULL,
  `url_moodle` VARCHAR(1000) NULL,
  `token` VARCHAR(200) NULL,
  PRIMARY KEY (`abbreviation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_integrazione`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_integrazione`.`Person` ;

CREATE TABLE IF NOT EXISTS `db_integrazione`.`Person` (
  `fiscal_code` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `zip_code` VARCHAR(45) NULL DEFAULT NULL,
  `gender` CHAR NULL DEFAULT NULL,
  `citizenship` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`fiscal_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_integrazione`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_integrazione`.`Professor` ;

CREATE TABLE IF NOT EXISTS `db_integrazione`.`Professor` (
  `idProfessor` INT NOT NULL,
  `position` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `office_hours` VARCHAR(45) NULL DEFAULT NULL,
  `Account_email` VARCHAR(100) NOT NULL,
  `Person_fiscal_code` INT NOT NULL,
  `Department_abbreviation` VARCHAR(50) NOT NULL,
  `profile_link` VARCHAR(500) NULL,
  PRIMARY KEY (`idProfessor`, `Account_email`, `Person_fiscal_code`, `Department_abbreviation`),
  INDEX `fk_Professor_Account1_idx` (`Account_email` ASC),
  INDEX `fk_Professor_Person1_idx` (`Person_fiscal_code` ASC),
  INDEX `fk_Professor_Department1_idx` (`Department_abbreviation` ASC),
  CONSTRAINT `fk_Professor_Account1`
    FOREIGN KEY (`Account_email`)
    REFERENCES `db_integrazione`.`Account` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Person1`
    FOREIGN KEY (`Person_fiscal_code`)
    REFERENCES `db_integrazione`.`Person` (`fiscal_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Department1`
    FOREIGN KEY (`Department_abbreviation`)
    REFERENCES `db_integrazione`.`Department` (`abbreviation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_integrazione`.`Organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_integrazione`.`Organization` ;

CREATE TABLE IF NOT EXISTS `db_integrazione`.`Organization` (
  `id_organization` INT NOT NULL,
  `company_name` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `training` LONGTEXT NULL DEFAULT NULL,
  `Account_email` VARCHAR(100) NOT NULL,
  `Person_fiscal_code` INT NOT NULL,
  PRIMARY KEY (`id_organization`, `Account_email`, `Person_fiscal_code`),
  INDEX `fk_Organization_Account1_idx` (`Account_email` ASC),
  INDEX `fk_Organization_Person1_idx` (`Person_fiscal_code` ASC),
  CONSTRAINT `fk_Organization_Account1`
    FOREIGN KEY (`Account_email`)
    REFERENCES `db_integrazione`.`Account` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organization_Person1`
    FOREIGN KEY (`Person_fiscal_code`)
    REFERENCES `db_integrazione`.`Person` (`fiscal_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_integrazione`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_integrazione`.`Student` ;

CREATE TABLE IF NOT EXISTS `db_integrazione`.`Student` (
  `serial_number` VARCHAR(45) NOT NULL,
  `Account_email` VARCHAR(100) NOT NULL,
  `Person_fiscal_code` INT NOT NULL,
  `Department_abbreviation` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`serial_number`, `Account_email`, `Person_fiscal_code`, `Department_abbreviation`),
  INDEX `fk_Student_Account1_idx` (`Account_email` ASC),
  INDEX `fk_Student_Person1_idx` (`Person_fiscal_code` ASC),
  INDEX `fk_Student_Department1_idx` (`Department_abbreviation` ASC),
  CONSTRAINT `fk_Student_Account1`
    FOREIGN KEY (`Account_email`)
    REFERENCES `db_integrazione`.`Account` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Person1`
    FOREIGN KEY (`Person_fiscal_code`)
    REFERENCES `db_integrazione`.`Person` (`fiscal_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Department1`
    FOREIGN KEY (`Department_abbreviation`)
    REFERENCES `db_integrazione`.`Department` (`abbreviation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_integrazione`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_integrazione`.`Staff` ;

CREATE TABLE IF NOT EXISTS `db_integrazione`.`Staff` (
  `id_staff` INT NOT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `Account_email` VARCHAR(100) NOT NULL,
  `Person_fiscal_code` INT NOT NULL,
  `Department_abbreviation` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_staff`, `Account_email`, `Person_fiscal_code`, `Department_abbreviation`),
  INDEX `fk_Staff_Account1_idx` (`Account_email` ASC),
  INDEX `fk_Staff_Person1_idx` (`Person_fiscal_code` ASC),
  INDEX `fk_Staff_Department1_idx` (`Department_abbreviation` ASC),
  CONSTRAINT `fk_Staff_Account1`
    FOREIGN KEY (`Account_email`)
    REFERENCES `db_integrazione`.`Account` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Staff_Person1`
    FOREIGN KEY (`Person_fiscal_code`)
    REFERENCES `db_integrazione`.`Person` (`fiscal_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Staff_Department1`
    FOREIGN KEY (`Department_abbreviation`)
    REFERENCES `db_integrazione`.`Department` (`abbreviation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
